services:
  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        platform: "linux/x86_64"
    command: tail -f /dev/null
    entrypoint: "/meguca/scripts/with_postgres.sh"
    volumes:
      - .:/meguca
