services:
  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        platform: "linux/x86_64"
    entrypoint: "/meguca/scripts/with_postgres.sh"
    command: "/meguca/meguca -a 0.0.0.0:8000"  # Pass address directly to binary
    volumes:
      - ./images:/meguca/images
